project_id = "cmqldzpqfkxpvnntmtcp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.undo-action]
    verify_jwt = false
